config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #for belongs_to  -- has_many realationship
    #as an review belongs to an album and an album has many reviews
    #check 'rake routes' to see how the reviews are nestes
  resources :albums do
    resources :reviews
  end
  root 'albums#index'
end

app/models/album.rb
class Album < ActiveRecord::Base
	belongs_to :user 
	belongs_to :genre
	has_many :reviews

	#has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	#validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

	#below used to associate paperclip based album_img with Album model
	#album_img added to Book via migration
								#album_index for images passed thru index 	#album_show for images on show pages
	has_attached_file :album_img, styles: { album_index: "350x350>", album_show: "250x250>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :album_img, content_type: /\Aimage\/.*\z/


end

app/models/genre.rb
class Genre < ActiveRecord::Base
	has_many :albums
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :album
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :albums
	has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
	#method below absolutely necessary to use find_album when necessary
	before_action :find_album, only: [:show, :edit, :update, :destroy]
	#prevents non-users from creating or editing
	before_action :authenticate_user!, only: [:new, :edit]

	def index
		#order albums by decsending order based on creation date
		if params[:genre].blank?
			@albums = Album.all.order("created_at DESC")
		else
			#grabs id of category being passed by genre selection
			@genre_id = Genre.find_by(name: params[:genre]).id
			#load books matching selected genre id
			@albums = Album.where(:genre_id => @genre_id).order("created_at DESC")
		end
	end

	def new
		#now have to create albums based on the current user params
		@album = current_user.albums.build
		#2d array matching all genre types to their ids
		@genres = Genre.all.map{ |c| [c.name, c.id] }
	end

	def create
		@album = current_user.albums.build(album_params)
		#needed to place genre id as part of album build params. as well as populate the genres link list items
		@album.genre_id = params[:genre_id]
		if @album.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def show
		if @album.reviews.blank?
			@average_review = 0
		else
			#display average rating of book reviews
			@average_review = @album.reviews.average(:rating).round(2)
		end
	end

	def edit
		#actual edit view stuff
		#need below line to make sure edit page has access to genre
		@genres = Genre.all.map{ |c| [c.name, c.id] }
	end

	def update
		#update now has access to genres to populate form
		@genres = Genre.all.map{ |c| [ c.name, c.id ] }
		if @album.update(album_params)
			redirect_to album_path(@album)
		else
			redirect_to 'edit'
		end
	end

	def destroy
		@album.destroy
		redirect_to root_path
	end
	
	private

		def album_params
												#album genre_id and album_img will not be build unless required here
			params.require(:album).permit(:title, :artist, :description, :genre_id, :album_img)
		end

		def find_album
			@album = Album.find(params[:id])
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	before_action :find_album
	before_action :find_review, only: [:edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]

	def new
		@review = Review.new
	end

	def create
		@review = Review.new(review_params)

		#need to save with respect to the current book and current user
		@review.album_id = @album.id
		@review.user_id = current_user.id
		#if saving redirect to show page
		if @review.save
			redirect_to album_path(@album)
		else
			render 'new'
		end
	end

	def edit
		#done with before action
	end

	def update
		#review found with before_action
		#redirect to album show if saving
		if @review.update(review_params)
			redirect_to album_path(@album)
		else
			render 'edit'
		end 
	end

	def destroy
		@review.destroy
		redirect_to album_path(@album)
	end

	private

		def review_params
			params.require(:review).permit(:rating, :comment)
		end

		def find_album
			@album = Album.find(params[:album_id])
		end

		def find_review
			@review = Review.find(params[:id])
		end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/albums/_album_form.html.erb
<%= simple_form_for @album, :html => { :multipart => true } do |f| %>
	<!-- select a genre_id from options genereated by @genres....defined in the albums controller-->
	<%= select_tag(:genre_id, options_for_select(@genres), :prompt => "Select Genre")%>
	<%= f.file_field(:album_img,)%>
	<%= f.input :title, label: "Album Title"  %>
	<%= f.input :artist, label: "Artist"%>
	<%= f.input :description, label: "Album Description" %>
	<%= f.button :submit %>
<% end %>

app/views/albums/edit.html.erb
<h1>Edit Album</h1>

<%= simple_form_for @album, :html => { :multipart => true } do |f| %>
	<!-- select a genre_id from options genereated by @genres....fill with enumerated @categories -->
	<%= f.select(:genre_id, @genres) %>
	<%= f.file_field :album_img %>
	<%= f.input :title, label: "Album Title"  %>
	<%= f.input :artist, label: "Artist"%>
	<%= f.input :description, label: "Album Description" %>
	<%= f.button :submit %>
<% end %>

app/views/albums/index.html.erb
<!-- only display current Genre if genre pramams have been passed-->
<% if params[:genre].blank? != true %>
	<h1 class="current_genre">Genre: <%= params[:genre] %></h1>
<% end %>
<div>
	<div>
	<% if @albums.count == 0 %>
		<h2>There are currently no albums in this category</h2>
	<% else %>
		<%# nested loop populates rows by 3 album objects%>
		<% @albums.each_slice(3) do |albums| %>
			<div class="row">
				<% albums.each do |album| %>
				<div class="col-md-4">
					<%= link_to image_tag(album.album_img, :class => "img-responsive index-tile shadow"), album_path(album.id) %>
				</div>
				<% end %>
			</div>
		<% end %>
	</div>
</div>
	<% end %>
<div class="row"><br></div>
<div class="row">
	<%= link_to "Add Album", new_album_path, :class => "btn btn-default" %>
</div>

app/views/albums/new.html.erb
<h1>New Album</h1>
<%= render 'album_form' %>

app/views/albums/show.html.erb
<div class="row">
	<div class="col-md-4">
		<div>
			<%= image_tag(@album.album_img.url(:album_show), :class => "index-tile")%>
		</div>
	</div>
	<div class="col-md-8">
		<h2><%= @album.title %></h2>
		<h2><%= @album.artist %></h2>
		<h3>Average Rating</h3>
		<div class="average-review-rating" data-score=<%= @average_review %> ></div>
		<span>Based on <%= @album.reviews.count %> Reviews </span>
		<!-- must have 'belongs_to :genre' in album.rb for genre to be accessable accross controllers -->
		<h3>Genre: <%= @album.genre.name %></h3>
		<p><%= @album.description %></p>
	</div>
</div>
<div class="row">
	<div class="col-md-4">
		<div>
			<%= link_to "Add Review", new_album_review_path(@album) %>
		</div>

		<div>
			<% #provided by review partial%>
			<%= render @album.reviews %>
		</div>
	</div>
</div>
<%= link_to "Back", root_path %>
<!-- Make sure a user is signed in before they can access update and destroy functionality-->
<% if user_signed_in? %>
<!-- Edit and Delete should only be available to the user who created the album-->
	<% if @album.user_id == current_user.id %>
		<%= link_to "Edit", edit_album_path(@album) %>
		<%= link_to "Delete", album_path(@album), method: :delete, data: { confirm: "Are you sure you wish to delete this album?" }%>
	<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>hXc Reviews</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
	        		<span class="sr-only">Toggle Navigation</span>
		        	<span class="icon-bar"></span>
		        	<span classhidden-lg ="icon-bar"></span>
	      		</button>
				<%= link_to "hXc reviews", root_path, class: "navbar-brand" %>
			</div>
			<!-- next div necessary for responsive collapse -->
			<div class="navbar-collapse collapse navbar-responsive-collapse">
				<ul class="nav navbar-nav navbar-right">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Genres<span class="caret"></span></a>
						<ul class = "dropdown-menu" role = "menu">
							<% Genre.all.each do |g| %>
							<!-- generate links based on genre name, route click to albums_path (index action) based on genre name params-->
							<% #blow set li to active if the passed genre [name] params == current iterations genre name%>
							<li class="<%= 'active' if params[:genre] == g.name %>">
								<%= link_to g.name, albums_path(genre: g.name ), class: "link" %>
							</li>
							<% end %>
						</ul>
					</li>
					<li> <%= link_to "Add Album", new_album_path %> 
					</li>
				</ul>
				<ul class="nav navbar-nav">
					<li><%= link_to "Sign Up", new_user_registration_path %></li>
					<% if user_signed_in? %>
						<li> <%= link_to "Sign Out", destroy_user_session_path, method: :delete %> </li>
					<% else %>
						<li> <%= link_to "Login", new_user_session_path %> </li>
					<% end %>
				</ul>
			</div>
		</div>
	</nav>
	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
	    
	<div class="container">
		<%= yield %>
	</div>


</body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for([ @album, @album.reviews.build ]) do |f| %>
	<div id="rating-form">
		<label>Rating</label>	
	</div>
	<%= f.input :comment %>
	<%= f.button :submit %>
<% end %> 

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/_review.html.erb
<div class="review-rating" data-score="<%= review.rating %>">
</div>

<p>
	<%= review.comment %>
</p>

<% if user_signed_in? %>
	<% if review.user_id == current_user.id  %>

		<% #review.album accesses current album, review references specific review instance %>
		<%= link_to 'Edit', edit_album_review_path(review.album, review) %>
		<%= link_to 'Delete', album_review_path(review.album, review), method: :delete, data: { confirm: "Are you sure?" } %>
	<% end %>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= simple_form_for([@album, @review]) do |f| %>

	<div id="rating-form">
		<label>Rating</label>	
	</div>
	<%= f.input :comment %>
	<%= f.button :submit %>

<% end %>

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>